# Generated by Django 2.0.1 on 2018-10-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessagePush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(blank=True, max_length=19, verbose_name='导入时间')),
                ('company_id', models.IntegerField(blank=True, verbose_name='公司Id')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名称')),
                ('phone_pay', models.CharField(blank=True, max_length=20, null=True, verbose_name='签约用户联系手机号')),
                ('user_id_kad', models.IntegerField(blank=True, verbose_name='kad系统用户唯一标识')),
                ('message', models.CharField(blank=True, max_length=200, null=True, verbose_name='推送具体消息')),
                ('is_read', models.IntegerField(blank=True, null=True, verbose_name='消息是否被查看')),
                ('read_date', models.DateTimeField(blank=True, max_length=19, null=True, verbose_name='客服查看时间')),
                ('reader', models.CharField(blank=True, max_length=200, null=True, verbose_name='查看人')),
                ('is_admin_read', models.IntegerField(blank=True, null=True, verbose_name='经理是否已读')),
                ('admin_read_date', models.DateTimeField(blank=True, max_length=19, null=True, verbose_name='经理查看时间')),
            ],
            options={
                'verbose_name': '系统消息推送',
                'verbose_name_plural': '系统消息推送',
            },
        ),
    ]
