# Generated by Django 2.0.1 on 2018-10-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_message_push', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='systemmessagepush',
            table='system_message_push',
        ),
    ]
