# Generated by Django 2.0.1 on 2018-10-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_role',
        ),
    ]
