# Generated by Django 2.0.1 on 2018-10-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountinfo',
            table='account_info',
        ),
        migrations.AlterModelTable(
            name='companyaccountinfo',
            table='company_account',
        ),
    ]
